grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/issuer: mongo-express-issuer
    hosts:
      - grafana.devopsheros.com
    tls:
      - secretName: mongo-express-certificate
        hosts:
         - grafana.devopsheros.com
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus-qa
        type: prometheus
        url: https://prom-qa.devopsheros.com
        access: proxy
      - name: Prometheus-prod
        type: prometheus
        url: https://prom-prod.devopsheros.com
        access: proxy


prometheus:
  enabled: false

ingress:
  subdomain: grafana

ingress-nginx:
  controller:
    service:
      loadBalancerIP: 35.238.115.26