{{- if eq .Values.grafana.enabled false -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongoexpress.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongoexpress.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongoexpress.name }}
    spec:
      containers:
      - name: {{ .Values.mongoexpress.name }}
        image: {{ .Values.mongoexpress.image }}
        ports:
        - containerPort: {{ .Values.mongoexpress.port }}
        #readinessProbe:
        #  httpGet:
        #    path: /
        #    port: {{ .Values.mongoexpress.port }}
        #  initialDelaySeconds: 15
        #  periodSeconds: 10
        #livenessProbe:
        #  httpGet:
        #    path: /
        #    port: {{ .Values.mongoexpress.port }}
        #  initialDelaySeconds: 15
        #  periodSeconds: 10
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb-credentials
              key: mongodb-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb-credentials
              key: mongodb-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb-credentials
              key: server
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb-credentials
              key: mongo-express-username
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb-credentials
              key: mongo-express-password
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongoexpress.name }}
spec:
  selector:
    app: {{ .Values.mongoexpress.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongoexpress.port }}
      targetPort: {{ .Values.mongoexpress.port }}
  type: ClusterIP

{{- end }}